#! /bin/sh

bspc monitor DVI-I-1 -d i ii iii iv 
bspc monitor DP-1 -d v vi vii viii 

# Visual options
# bspc config top_padding         15
# bspc config border_width        10 
# bspc config window_gap          30
# bspc config split_ratio         0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true
# bspc config focus_follows_pointer true
# bspc config auto_alternate true
# bspc config auto_cancel true
# bspc config normal_frame_opacity 0.0
# bspc config focused_frame_opacity 0.1
# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
export PANEL_FIFO PANEL_HEIGHT PANEL_FONTE_FAMILY

bspc rule -a gimp floating=on

panel &
