#! /bin/sh

# Variables
PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=36
PANEL_UNDERLINE_HEIGHT=2

# You need lemonbar-xft-git for these to work
PANEL_FONT_FAMILY="CamingoCode:size=9"
PANEL_ICON_FAMILY="FontAwesome:size=11"
export PANEL_FIFO PANEL_HEIGHT PANEL_UNDERLINE_HEIGHT PANEL_FONT_FAMILY PANEL_ICON_FAMILY

bspc config window_gap 18
bspc config top_padding $(expr $PANEL_HEIGHT + $PANEL_UNDERLINE_HEIGHT + 4)

# Colors
bspc config focused_border_color "#e5ebf1"
bspc config active_border_color "#aabcce"
bspc config normal_border_color "#aabcce"

bspc monitor DVI-I-1 -d $(echo -e '\uf0ac') $(echo -e '\uf121') $(echo -e '\uf120')  $(echo -e '\uf075')
bspc monitor DP-1 -d $(echo -e '\uf0ac') $(echo -e '\uf121') $(echo -e '\uf120')  $(echo -e '\uf075')

bspc rule -a gimp state=floating
bspc rule -a mpv state=floating

panel &
