#!/bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' > "$PANEL_FIFO" & # See xtitle-git@AUR
clock -sf 'S%H:%M' > "$PANEL_FIFO" & # See sutils-git@AUR

. panel_colors

cat "$PANEL_FIFO" | panel_bar \
  | lemonbar -g x$PANEL_HEIGHT \
             -f "$PANEL_FONT_FAMILY" \
             -f "$PANEL_ICON_FAMILY" \
             -F "$COLOR_FOREGROUND" \
             -B "$COLOR_BACKGROUND" \
             -u "$PANEL_UNDERLINE_HEIGHT" &
# We could start pipiping to sh and use lemonbar's %{A} to make things clickable

wait
