#! /bin/sh

. panel_colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "

while read -r line ; do
  case $line in
    S*)
      # clock output
      sys="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
      ;;
    T*)
      # xtitle output
      title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
      ;;
    W*)
      # bspwm internal state
      wm=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [mM]*)
            [ $num_mon -lt 2 ] && shift && continue
            case $item in
              m*)
                # inactive monitor
                FG=$COLOR_INACTIVE_MONITOR_FG
                BG=$COLOR_INACTIVE_MONITOR_BG
                ;;

              M*)
                # active monitor
                FG=$COLOR_ACTIVE_MONITOR_FG
                BG=$COLOR_ACTIVE_MONITOR_BG
                ;;
            esac
            # wm="$wm %{F$FG}%{B$BG} ${name} %{B-}%{F-}  "
            ;;
          [fFoOuU]*)
            U=$COLOR_BACKGROUND
            case $item in
              f*)
                FG=$COLOR_FREE_FG
                BG=$COLOR_FREE_BG
                ;;
              o*)
                FG=$COLOR_OCCUPIED_FG
                BG=$COLOR_OCCUPIED_BG
                ;;
              u*)
                FG=$COLOR_URGENT_FG
                BG=$COLOR_URGENT_BG
                ;;
              [FOU]*)
                FG=$COLOR_FOCUSED_FG
                BG=$COLOR_FOCUSED_BG
                U=$COLOR_FOCUSED_UNDERLINE
                ;;
            esac
            wm="${wm}%{F$FG}%{B$BG}%{U$U}%{+u}${PADDING}${name}${PADDING}%{-u}%{B-}%{F-}"
            ;;

          L*)
            # layout
            # wm="${wm}%{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac
  BAR="%{l}${wm}%{c}${title}%{r}${sys}"
  printf "%s\n" "${BAR}%{S+}${BAR}"
done
