# zplugin
source ~/.zplugin/bin/zplugin.zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory nomatch
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/fkurkowski/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

zplugin light zsh-users/zsh-autosuggestions
zplugin light zdharma/fast-syntax-highlighting
zplugin light zdharma/history-search-multi-word
zplugin light supercrabtree/k

zplugin ice pick"async.zsh" src"pure.zsh"
zplugin light sindresorhus/pure

export EDITOR=vim
export VISUAL=$EDITOR
export BROWSER=firefox

export PATH=$HOME/bin:/usr/.local/bin:$HOME/.local/bin:$PATH
